### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by Legendsevl** [phflot/flow_registration#21]
Hi phflot, 
     This work of yours is very good. I'd like to ask, I see some GPU-related stuff in the code, can this work be accelerated with GPU and how?

**Comment by phflot** [comment]
Hi @Legendsevl ,
thank you for the feedback, yes, I did some experiments with gpu arrays and the `OF_solver_GPU` function in `get_displacements` should be usable in a similar way as the cpp code. I'll have to check the state of the gpu version, you would want to implement something like a red-black gauss seidel solver, but in the code it would update the complete images because I did not see a benefit compared to the cpp code: If you use cc-prealignment and only refine the result on a few levels, you'll achieve real time speed for 512x512. 
What type of data are you working with and do you get reasonable results with the code?
Best wishes,
Philipp

**Comment by Legendsevl** [comment]
Okay, thank you for your answer
